SHOW_GUI = True
TRAINING_NUM = 1
GENERATION_NUMBER = 3
POPULATION = 200
MUTATION_PARAM = 0.85
LOG_WEIGHTS_GENERATION = 10
SNAKE_LENGTH = 45
# MUTATION
DONT_MUTATE = 2
PITY_TIMER = 1000

# REWARDS / PUNISHMENT CONSTANTS
RESET_PITY_ON_EAT = True
RESET_PITY_ON_NEW = True
REWARD_FOOD_EAT = 10
REWARD_DISTANCE_TRAVELED = 1
REWARD_CLOSER_TO_FOOD = 0
REWARD_NEW_TILE_VISITED = 0
PUNISH_ALREADY_VISITED = 0
PUNISH_TIMER_ALREADY_VISITED = 100
PUNISH_FURTHER_FROM_FOOD = 0
PUNISH_DEATH = 0
